name: Binaries
on:
  release:
    types:
      - created
jobs:
  release:
    name: Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - 386
          - amd64
          - arm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Test
#        run: go test -v -p=1 -timeout=0 ./...
      - name: Release
        uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: .
          binary_name: wpld
          ldflags: -s -w
          extra_files: LICENSE README.md
